export const data = [
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "GPU",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "16GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "16GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "GPU",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "16GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "AMD",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "GPU",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "AMD",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "AMD",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "GPU",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "AMD",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "AMD",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "08GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "24GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "GPU",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "24GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "24GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "24GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
    {
        "display_Name": "SGTPUL1",
        "node_Name": "SGTPUL1",
        "node_IP": "192.168.0.1",
        "RAM": "24GB",
        "CPU": "24CPU",
        "Rack": "R1A-45",
        "Mac_Address": "d4.d5.47.75.22.e2",
        "Node_Type": "Workstation",
    },
]